# Generated by Django 4.2 on 2023-10-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_add_category_product_subcategory_delete_web_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='date',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
