# Generated by Django 4.2 on 2023-10-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_subcategory_date_subcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='slue',
        ),
    ]
