# Generated by Django 4.2 on 2023-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_name_subcategory_slue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='category',
            name='slue',
            field=models.CharField(max_length=50),
        ),
    ]
