# Generated by Django 4.2 on 2023-10-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_date_product_price_alter_category_slue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add',
        ),
    ]
